[features]
seeds = false
skip-lint = false

[programs.localnet]
contest_nft = "9r5T4DCQoY4sAtJm9uH2j7KVahMhyH1qKbd32EsGdaNx"

[programs.devnet]
contest_nft = "9r5T4DCQoY4sAtJm9uH2j7KVahMhyH1qKbd32EsGdaNx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
